### ISSUE TITLE
segmentation support & BTL Cert

### ISSUE THREAD

**Issue by cyberumut** [bacnet-stack/bacnet-stack#571] opened 2024-02-09 20:02 UTC
When will segmentation be supported?
And does bacnet stack pass BTL Certification  ?

what i need for BTL Certification ?

**Comment by cyberumut** [comment] 2024-02-09 20:09
where to i look for segmentation ? i want add segmentation for bacnet stack lib

**Comment by MightyPork** [comment] 2024-02-09 20:22
unfortunately not supported yet. there was some work but nothing finished.
this is a duplicate of #362 #417

**Closed by MightyPork** 2024-02-09 20:22 UTC

**Comment by skarg** [comment] 2024-02-12 16:10
BTL testing and certification information is available from the https://btl.org/ website.

This BACnet Stack protocol library has been used in many products as the basis for their BACnet functionality, and those products have passed BTL testing.  Any defects found in this library via BTL testing are corrected.  However, a lot of the BACnet functionality depends on how the vendor modeled their device, the objects and properties and services and datalinks they chose to use, and a variety of other variables.
